version: '3'
services:
  metabase:
    image: metabase/metabase:v0.46.6
    container_name: metabase_app
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_password
      MB_DB_HOST: db
    depends_on:
      - db
    volumes:
      - metabase-data:/metabase.db

  db:
    image: postgres:13
    container_name: metabase_db
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  metabase-data:
  postgres-data: